---
- hosts: all
  connection: local
  become: true
  become_method: sudo
  vars:
    subscription_id: c0a5e7f3-ecf4-403c-a540-92d7dbd440ee
    tenant: 041f60c7-63e9-4bc4-9660-a9c74ad21061
    client_id: 292a04e5-df00-475e-b961-1b2d5c8275f5
    secret: <uAM8Q~pmSlCKSJOtb_qNpzNi2GkssxNbI2bl6bKo
  
  pre_tasks:
   - block:
     - fail:
        msg: "Too many hosts"
       when: ansible_play_hosts_all | length > 1       
     run_once: true 

  tasks:
  - name: Start virtual machine
    azure_rm_virtualmachine:
      resource_group: anavid
      name: "{{inventory_hostname}}"
      started: yes
